language: python
python:
- '3.9'
install: pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  app: rustfiends
  run:
  - python manage.py migrate
  api_key:
    secure: q3hbCNQOpzDHkUNkbF1y4K9Urwddpb5RuD7gkjh+KNNvEOreDEvwB996qvRcbVE0nh9kzH+dyW7HsZ7IfXczvTfqLzGqPApvYQGcemqybepezAw+xJFGqTPchkxzwg1h7XSfABwzSV8JoCc3AdNtsEIXwU8OOPsyK3zqdstcWoMvnD7t/1jchvoTR+TTFRWT2rxnIXApwrbgw+qsuufC3Efq2hWxbuhHMw8Dl7ZNcKEH3v3vyW8R4rScDvgDde/C5mZbSCUA0QQ/ej38alODmw2nLx79Ld2xKOCES0+URoR2fhUejUodPtMJsuWbfJoeaAW8B3pgyZvlC7BrtilAOOO7/G6Ifl/1dkvb8jjBovpbe5ZD5cuHC1eiKfeJXJZS5n9JWp5X3TstljhzHL2L/+lD/HP7wDc05o4aUPkiz45YhebBY9alHxnSk6Wp8nItFJTAJrdGfrhW9k3f9qklLzNWldR6Qn60bRZBa8gIS6SSaR1IlT1v2lk0gGRYvwJ9ni+NK/mzdixcG7KK4MBS/DKOyoo0bd1kXKhgMWIIk5d+X1ELjSrWtUXHvnftsxW3H6HIOZNEPpk31vuKPsub+b+hnPb+Ju+l12sNDik1clfVcWwSLADbG+W3u38tvVPjK6nvPkqJ9jiO2fq7kVGVX8GkLKuy+aI1aGCe7c2WXjw=
