language: python
python:
- '3.9'
install: pip install -r requirements.txt
script:
- python manage.py test
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  app: rustfiends
  run:
  - python manage.py migrate
  api_key:
    secure: GLyTgCC0V8D4Dr5mxAnGFK5ekJuR+jCuXPK8xqejsUmYTHwyx0yr8m3Dhbc331FyrWR5vfAX2DpK+B92Lxqc2iyZR+vZEsodKhiLC9iG4BXoWTfNIYw1+wLPnbb+92NxA8Tw96cmc3tNvnG49nOc5+tVeEk2ptCSSnlmn1Uj+QB2VKe//5nKLs2C1exHEJwxAJyRUXXu6AkexiX9L/oCRV4GUVb21CiSvKIYvPzL7/hVBuxVmc/Ok1BMNzJ5tPSg7iwIOEPhjuMm6ZNzhSC9Cg5/MD/s9le81+5GJUswryn88IcRx+NOga0BDcMdlrs9YqyssQSSJyM7kjRJ55ugk0KbK6f5P/DvnFhxrlY2/VegSwFwwt1mvzG2z5BDp2CrAG0ZcIjSI+PHV4ubKH7dXQAs+sjpO0RVTH4Odk0udSnIhCcjOqjOdHF7DNFsMkJ5W6BEt71M40tXeMDKVnUBmyqmWjf4adAwYqV70bErkWEMKQwlKoexRsbDGZRyNMhUhGkGqk3CyxRCZeUzdy/pwRGI9pLPV/1ViWyqrRWfWt6PQvepCn3rdt3hfTBg0qc0HIaUy7yMBD5ZjXam5aU84VfPTgn+p4TpgvUweic7qAH0ZyP495DXbCbZxaSpLO5UzG7focGtlhW3o5PUoOMkSAPg6K9VFvL0TgT/BH/M75E=
