# Generated by Django 3.0.2 on 2020-01-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag_line',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
