# Generated by Django 3.0.2 on 2020-01-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='county_or_state',
            field=models.CharField(blank=True, max_length=50, verbose_name='County / State'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='street_address1',
            field=models.CharField(max_length=200, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='street_address2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='town_or_city',
            field=models.CharField(max_length=50, verbose_name='Town / City'),
        ),
    ]
