# Generated by Django 3.0.2 on 2020-01-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200116_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='primaryCategory',
            new_name='featured',
        ),
    ]
