# Generated by Django 3.0.2 on 2020-01-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200116_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-title']},
        ),
    ]
